analyzer:
  errors:
    implementation_imports: ignore
    lines_longer_than_80_chars: ignore
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    use_build_context_synchronously: false


    

