include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    use_build_context_synchronously: false
    max_line_length: 120
    trailing_comma: false


    

